language: R
sudo: required
warnings_are_errors: true

env: 
  global:
    - CRAN: https://cran.rstudio.com
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  # - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get update -q
  - sudo apt-get install -qq libzmq3-dev
  - sudo apt-get install -qq libsodium-dev

r_packages:
  - assertthat
  - pbdZMQ
  - sodium

r_check_args: --no-build-vignettes --no-manual

notifications:
  email:
    on_success: no
    on_failure: no

